# Generated by Django 5.0.4 on 2024-07-11 12:57

from django.db import migrations


def calculate_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone_model = apps.get_model("main_app", "Smartphone")

    phones = smartphone_model.objects.all()

    for phone in phones:
        phone.price = len(phone.brand) * MULTIPLIER
    smartphone_model.objects.bulk_update(phones, ["price"])


def generate_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")

    phones = smartphone_model.objects.all()

    for phone in phones:
        if phone.price >= 750:
            phone.category = "Expensive"
        else:
            phone.category = "Cheap"
    smartphone_model.objects.bulk_update(phones, ["category"])


def reset_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")

    phones = smartphone_model.objects.all()

    for phone in phones:
        phone.price = smartphone_model._meta.get_field("price").default
        phone.category = smartphone_model._meta.get_field("category").default
    smartphone_model.objects.bulk_update(phones, ["price", "category"])



def set_price_and_category(apps, schema_editor):
    calculate_price(apps, schema_editor)
    generate_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reset_price_and_category)
    ]
